remote_theme: pages-themes/midnight@v0.2.0
title: Jabin's Tech
description: [My PC](/mypc) | [jabinstech.net](https://jabinstech.net/)
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
